### ISSUE TITLE
Autocompletion not permitted by browser for API field

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2125] opened 2018-11-14 12:53 UTC
The API field does not allow browser to auto-complete field with previously used API links. It is apparently configured as a password field, that is not permitted to store previous data.

Please change to allow the field auto-completion.

![screenshot from 2018-11-14 13-50-57](https://user-images.githubusercontent.com/1583873/48483734-8dc09a80-e814-11e8-899a-f999093ba0e6.png)

**Comment by digitalPlayer1125** [comment] 2020-09-30 12:02
Seems like a duplicate #2081 ?

**Comment by iamareebjamal** [comment] 2020-10-14 05:48
Duplicate of #2081

**Closed by iamareebjamal** 2020-10-14 05:48 UTC
Labels: Codeheat, bug
