### ISSUE TITLE
Implement filters as links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-wsgen#2127] opened 2018-11-30 02:51 UTC
Currently only some filters have actual links. The goal is that we can link directly to filter sections. Please implement links e.g. on the schedule page 
* the dates
* the filters
![screenshot from 2018-11-30 09-25-47](https://user-images.githubusercontent.com/1583873/49265236-45e47900-f48c-11e8-883a-1f20612f0f64.png)

Same applies to sidebar filters. All filters should be linkified.

![screenshot from 2019-02-18 14-28-14](https://user-images.githubusercontent.com/1583873/52932042-8b2c8e80-3389-11e9-98fd-1710560b439a.png)

**Comment by hoangdatngo** [comment] 2020-01-10 13:25
I want to work on this issue

**Comment by aryanguls** [comment] 2020-01-14 18:11
@mariobehling Sir I would like to work on this issue. I will solve this issue as soon as possible.

**Comment by Hry789** [comment] 2020-01-21 13:51
can i have the code please

**Comment by djcruz93** [comment] 2020-10-30 09:02
@iamareebjamal this issue is already resolved by me. Seems to be a duplicate of #2139

**Closed** 2020-10-30 10:34 UTC
Labels: Codeheat, Priority: High, bug, enhancement
